### ISSUE TITLE
--compare-model should filter for compact single-component sources, at least as an option

### ISSUE THREAD

**Issue by o-smirnov** [Athanaseus/aimfast#46]
Only makes sense to compare point source fluxes really. So this should be the default behaviour.

**Comment by o-smirnov** [comment]
See this comment: https://github.com/o-smirnov/meerkat-open-time/issues/18#issuecomment-693465775

**Comment by Athanaseus** [comment]
This is the default behaviour. To compare all sources regardless of shape add `-as`.
