### ISSUE TITLE
No Output plots created from --compare-models

### ISSUE THREAD

**Issue by Kincaidr** [Athanaseus/aimfast#55]
When i run the command:

`aimfast --compare-models image1-pybdsf.lsm.html image2-pybdsf.lsm.html --html-prefix cluster -fp log`
i get:

![image](https://user-images.githubusercontent.com/53697426/132219525-cfdf4ab0-e034-45a4-ad03-f1c882ebe862.png)

Check:

`WARNING - No photometric plot created for Zwcl2341-1_UGMRT_robust0_tap7-MFS-image.fitsimage.rgd.conv-pybdsf.lsm.html`
`WARNING - No plot astrometric created for Zwcl2341-1_UGMRT_robust0_tap7-MFS-image.fitsimage.rgd.conv-pybdsf.lsm.html`

So no `.html` flux plot is created, only fidelity_results.json file

**Comment by Athanaseus** [comment]
Do the sources in the catalog by chance all have some sort of shape?
If that's the case try `-as` for all sources without filtering sources with some shape.

The catalogs being cross-matched might not have matching sources, if that's unlikely you can increase the cross-matching tolerance `-tol`.

Also, you can check what's in the json file and if everything is appropriate.

Finally, you can send through the models I can try to reproduce this.

**Comment by Athanaseus** [comment]
It looks like only one source matched, that's why no plotting was done.

**Comment by Kincaidr** [comment]
> Do the sources in the catalog by chance all have some sort of shape?


How would i check this?
>  If that's the case try -as for all sources without filtering sources with some shape.

I added the `-as` command still same output.

The json file seems fine:
[fidelity_results.txt](https://github.com/Athanaseus/aimfast/files/7117656/fidelity_results.txt)

The images and sky model .lsm files are located here: `/net/ike/vault-ike/kincaid/spx2/img`

image1: image_DD_beam_2poly_beam_brighptsrc5_mask_uvsel_gmrt.restored.fits.image_J2000.rgd.conv.fits
image2: Zwcl2341-1_UGMRT_robust0_tap7-MFS-image.fitsimage.rgd.conv.fits

**Comment by Athanaseus** [comment]
> How would i check this?

You can use `tigger` to view your catalogs. Also, the `fidelity_results.txt` should have all properties of sources (flux, position, shape etc.)

Looking at the images they seem to be inconsistent in terms of the sources, the one only has sources mostly populated on the centre but less away from the centre while the other has more sources in general and away from the centre.

```
aimfast.aimfast - 2021-09-07 23:33:06,845 INFO - Model 1 source: 3986
aimfast.aimfast - 2021-09-07 23:33:06,846 INFO - Model 2 source: 1063
```
 This also confirms that one catalog has ~4-times the number of sources of the other. NB: That's according to `pybdsf`.
Using `-as -tol 1` where to is the tolerance in arcsec of separation in cross-matching sources. You can increase this value, but it increases the chances of false matches.
I get the following:
![Screenshot from 2021-09-07 23-39-35](https://user-images.githubusercontent.com/16665629/132414925-5665a92f-459c-4633-8e5b-a225151fdcd8.png)

These results don't look good. One can also notice that the more off-axis the source the more the discrepancy in the flux (yellowish data points). Also looking close at the one source and using it's coordinates i did a quick check of the region using subimage stats `-cps  4684,2323,200`

![Screenshot from 2021-09-08 00-00-47](https://user-images.githubusercontent.com/16665629/132416429-f8dda745-477c-42e6-998d-51d9f0e406fc.png)

![Screenshot from 2021-09-08 00-04-00](https://user-images.githubusercontent.com/16665629/132416470-20998ffd-4867-43f5-9f8b-d9e4d6fa13e9.png)

The source in the second frame is faint but still was picked up by the source finder. The properties do not match, except they occupy the same position.

![Screenshot from 2021-09-07 23-39-49](https://user-images.githubusercontent.com/16665629/132415078-ec05790b-fe7c-411c-9267-d1918c9251b0.png)

This also shows that the other model is missing sources.

**Comment by Kincaidr** [comment]
Ok it works with `-tol 1`

![image](https://user-images.githubusercontent.com/53697426/132574324-4ebf6faf-8057-4059-bde8-776a6211e437.png)

The graph appears to be the same as yours, But why are my stats different to yours?

I ran:

`aimfast --compare-models image_DD_beam_2poly_beam_brighptsrc5_mask_uvsel_gmrt.restored.fits.image_J2000.rgd.conv-pybdsf.lsm.html Zwcl2341-1_UGMRT_robust0_tap7-MFS-image.fitsimage.rgd.conv-pybdsf.lsm.html -as -tol 1 --html-prefix cluster -fp log`

> Also looking close at the one source and using it's coordinates ...

This source you looked at, was it very far off-axis?

**Comment by Athanaseus** [comment]
> The graph appears to be the same as yours, But why are my stats different to yours?

I just made some updates that will be pushed to master soon still in branch `ai_updates`. Basically, it was showing stats for the `-fp inout`.

> This source you looked at, was it very far off-axis?

Yes, as indicated in the source info dis-off-axis is `0.74` deg, that's almost a degree from the phase centre.

PS: Also the data points are coloured with the distance from the phase centre. The more close to the centre (dark blue ) sources seem to correlate well. I have also added this filter `--only-off-axis 0.4` which will plot only cross-matched sources that have a lesser distance than this in degrees (user can decide cut-off), just in case you want to focus on the central region only. (I will also add an option to just exclude a specific list of sources if that will be useful)

![Screenshot from 2021-09-08 23-10-45](https://user-images.githubusercontent.com/16665629/132585683-33640adc-0da7-40b6-a6f9-73cd4c16e82c.png)

**Comment by Kincaidr** [comment]
> These results don't look good. 

Yes, this is actually expected since im using these images for spectral index map and so the gmrt image is at a different frequency to meerkat hence this comparison was a pointless exercise. I must compare meerKAT to NVSS and gmrt to some well known secondary calibrator for this comparison to be meaningful.
